### ISSUE TITLE
Better handling of test failure logs

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#212]
Right now, if there are test failures (and actually, even if there aren't) we dump them to console. Several problems with that:

* <s>If something is interrupted with ctrl-c, it winds up getting dumped after *next* test run</s> (I'm wrong about that. But often run data with no number suffix gets dumped, I'm just not sure where it's coming from)
* The logfiles are often freaking *huge*
* If a log was written but not detected during a test failure, it still gets dumped
* A lot that hasn't been marked for a specific failure still gets dumped
* We don't put the test name/location with the logs, so it's mostly a guess -- or you can match up the sequence number to the failure, but still, ew

We should leave the logs in a known place at the end of the test run, print its location if and only if there are one or more logs, and have Github Actions upload those logs as artifacts. Then we don't need to scroll through all of it in the Github Actions console.

**Comment by noahgibbs** [comment]
Reference of not-great output: https://github.com/scarpe-team/scarpe/actions/runs/5213564306/jobs/9408717569?pr=213

**Comment by noahgibbs** [comment]
Specific problems shown there:

There are two tests that show a failure printed to console but do *not* fail the test. One or the other of those things should change. Example:

~~~
TestControlInterface
  test_assert_widget                                              PASS (1.71s)
Error occured: /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/control_interface_test.rb:34:in `return_results': Returning more than one set of results! Bad! (RuntimeError)
	from /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/control_interface_test.rb:86:in `block in return_when_assertions_done'
	from /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/web_wrangler.rb:83:in `each'
	from /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/web_wrangler.rb:83:in `block in initialize'
	from /Users/runner/work/scarpe/scarpe/vendor/bundle/ruby/3.2.0/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:64:in `block in bind'
	from /Users/runner/work/scarpe/scarpe/vendor/bundle/ruby/3.2.0/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:45:in `webview_run'
	from /Users/runner/work/scarpe/scarpe/vendor/bundle/ruby/3.2.0/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:45:in `run'
	from /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/web_wrangler.rb:317:in `run'

(...)

Going to terminate
~~~

Other example:

~~~
  test_assert_dom_html_update                                     PASS (1.90s)
Error occured: /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/control_interface_test.rb:34:in `return_results': Returning more than one set of results! Bad! (RuntimeError)
	from /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/control_interface_test.rb:86:in `block in return_when_assertions_done'
	from /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/web_wrangler.rb:83:in `each'
	from /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/web_wrangler.rb:83:in `block in initialize'
	from /Users/runner/work/scarpe/scarpe/vendor/bundle/ruby/3.2.0/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:64:in `block in bind'
	from /Users/runner/work/scarpe/scarpe/vendor/bundle/ruby/3.2.0/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:45:in `webview_run'
	from /Users/runner/work/scarpe/scarpe/vendor/bundle/ruby/3.2.0/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:45:in `run'
	from /Users/runner/work/scarpe/scarpe/lib/scarpe/wv/web_wrangler.rb:317:in `run'

(...)

Going to terminate
~~~

**Comment by noahgibbs** [comment]
There is also a test failure:

TestWebWrangler
  test_ww_redraw_basic                                            PASS (0.00s)
  test_empty_app                                                  FAIL (2.91s)
        Scarpe app returned no status code!
        /Users/runner/work/scarpe/scarpe/test/test_helper.rb:171:in `block in test_scarpe_app'
        /Users/runner/work/scarpe/scarpe/test/test_helper.rb:32:in `with_tempfile'
        /Users/runner/work/scarpe/scarpe/test/test_helper.rb:[11](https://github.com/scarpe-team/scarpe/actions/runs/5213564306/jobs/9408717569?pr=213#step:4:12)6:in `test_scarpe_app'
        /Users/runner/work/scarpe/scarpe/test/test_helper.rb:58:in `block in test_scarpe_code'
        /Users/runner/work/scarpe/scarpe/test/test_helper.rb:32:in `with_tempfile'
        /Users/runner/work/scarpe/scarpe/test/test_helper.rb:57:in `test_scarpe_code'
        /Users/runner/work/scarpe/scarpe/test/test_web_wrangler.rb:8:in `test_empty_app'

Presumably that corresponds to the logs printed to console with the 000 suffix.

Here's one of them:

~~~
Test failure log "/Users/runner/work/scarpe/scarpe/logger/test_failure_000.log":

DEBUG  WV::WebWrangler : Creating WebWrangler...
DEBUG  WV::WebWrangler : Run...
DEBUG  WV::WebWrangler::DOMWrangler : Requesting DOM replacement...
DEBUG  WV::WebWrangler::DOMWrangler : Requesting redraw with 1 waiting changes - need to schedule something!
DEBUG  WV::WebWrangler::DOMWrangler : Requesting redraw with 1 waiting changes - scheduling a new redraw for them!
DEBUG  WV::WebWrangler : Scheduled JS: (0)
(function() {
  var code_string = "document.getElementById('wrapper-wvroot').innerHTML = `<div></div>`; true";
  try {
    result = eval(code_string);
    scarpeAsyncEvalResult("success", 0, result);
  } catch(error) {
    scarpeAsyncEvalResult("error", 0, error.message);
  }
})();

DEBUG  WV::WebWrangler : Destroying WebWrangler...
~~~

And the other is blank, possibly for lack of Webview API calls.

~~~
Test failure log "/Users/runner/work/scarpe/scarpe/logger/test_failure_wv_api_000.log":


rake aborted!
Command failed with status (1)
/Users/runner/work/scarpe/scarpe/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/runner/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle:25:in `load'
/Users/runner/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle:25:in `<main>'
~~~

Some of this would be improved by this PR's recommendations -- e.g. the two spurious logfiles with *no* numeric prefix, logs could be file attachments instead of console output. But some of it isn't directly fixed by that (e.g. are those not test failures and should be? Probably.)
