### ISSUE TITLE
WebWrangler failure if you create widgets and immediately start updating them

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#225]
I found this while building the examples de-duper.

~~~
Shoes.app do
  p = para "Hello"
  p.replace "Goodbye"
end
~~~

This should, of course, do the right thing instead of saying WebWrangler isn't running yet.

Here's what I currently see:

~~~
noah@Noahs-MacBook-Pro-3 scarpe % ./exe/scarpe --dev ./bad_example.rb
/Users/noah/src/shoes/scarpe/lib/scarpe/wv/web_wrangler.rb:171:in `eval_js_async': WebWrangler isn't running, so evaluating JS won't work! (RuntimeError)
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/web_wrangler.rb:614:in `schedule_waiting_changes'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/web_wrangler.rb:540:in `promise_redraw'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/web_wrangler.rb:472:in `request_change'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/web_wrangler.rb:394:in `dom_change'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/web_wrangler.rb:645:in `inner_html='
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/para.rb:24:in `properties_changed'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/widget.rb:57:in `block in initialize'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/display_service.rb:77:in `block in dispatch_event'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/display_service.rb:77:in `each'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/display_service.rb:77:in `dispatch_event'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/display_service.rb:143:in `send_shoes_event'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/widget.rb:155:in `block in method_missing'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/widget.rb:158:in `method_missing'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/para.rb:43:in `replace'
	from /Users/noah/src/shoes/scarpe/bad_example.rb:3:in `block in <top (required)>'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/app.rb:48:in `instance_eval'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/app.rb:48:in `init'
	from /Users/noah/src/shoes/scarpe/lib/scarpe.rb:33:in `app'
	from /Users/noah/src/shoes/scarpe/bad_example.rb:1:in `<top (required)>'
	from ./exe/scarpe:90:in `load'
	from ./exe/scarpe:90:in `<main>'
~~~

**Comment by noahgibbs** [comment]
Right now we wait for the Scarpe.app block to fully execute before we start sending stuff to Webview. That way we can do one big "here's the DOM" call.

Unfortunately, as the example above indicates, there's a problem with that -- we may be partway through that block and want to send an update. Right now that doesn't work at all.

One way to handle it would be to build the DOM incrementally at first. That gets ugly because it's a lot more messages back and forth. And it would be entirely possible to have an early handler fire before the later widgets are fully instantiated -- remember you can put things that cause significant delays in that block, especially on relay-Webview display programs where you won't block Webview's event loop and get a segfault.

We could have the DOMWrangler embargo updates for awhile -- keep track of them, but don't start scheduling them until we've fully executed the initial Scarpe.app block.

That's not perfect. If you had a program that just hung out in the block forever, looping or something, it would never display. But it's probably better than trying the incremental build, at least for now. That could change in the future if we have examples/apps that expect to be allowed to just loop inside there forever.

**Comment by noahgibbs** [comment]
Hm. I think the right choice will be to keep track of whether we've sent the DOM body-replacement call, and not send any other DOM updates until we do (like, ignore/cancel those updates.) It should be fine to send an initial DOM body-replacement with non-default values (e.g. a para whose text has been replaced.) And then we'll just send the DOM body-replacement at the end of the Shoes.app block.
