### ISSUE TITLE
Bloops is making me feel stupid

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#271]
I'm getting an error when I try to bundle with the new bloopsaphone dependency. I uninstalled and reinstalled portaudio thinking that would help (homebrew), but no avail. I'd love to learn what I'm doing wrong and make a note of it in case anyone else runs into this! :) 

initial bundle error

```
scarpe|main ⇒ bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake 13.0.6
Using bundler 2.4.10
Using chunky_png 1.4.0
Using ansi 1.5.0
Using fastimage 2.2.7
Using ffi 1.15.5
Using builder 3.2.4
Using color 1.8
Using matrix 0.4.2
Using io-console 0.6.0
Using json 2.6.3
Using array_include_methods 1.4.0
Using ast 2.4.2
Using little-plugger 1.1.4
Using os 1.1.4
Using minitest 5.18.1
Using rouge 3.30.0
Using parallel 1.23.0
Using facets 3.1.0
Using language_server-protocol 3.17.0.3
Using libui 0.0.15
Using multi_json 1.15.0
Using equalizer 0.0.11
Using unicode-display_width 2.4.2
Using racc 1.7.1
Using method_source 1.0.0
Using rainbow 3.1.1
Using redcarpet 3.6.0
Using regexp_parser 2.8.1
Using glimmer 2.7.3
Using ruby-progressbar 1.13.0
Using sqlite3 1.6.3 (arm64-darwin)
Using yard 0.9.34
Using ffi-compiler 1.0.1
Using minitest-reporters 1.6.0
Using logging 2.3.1
Using rexml 3.2.5
Using perfect-shape 1.0.8
Using nokogiri 1.15.2 (arm64-darwin)
Using parser 3.2.2.3
Using super_module 1.4.1
Using reline 0.3.5
Using webview_ruby 0.1.2
Fetching glimmer-dsl-libui 0.5.24
Using irb 1.7.0
Using rubocop-ast 1.29.0
Using debug 1.8.0
Using rubocop 1.54.0
Using rubocop-shopify 2.14.0
Installing bloops 0.5 with native extensions
Installing glimmer-dsl-libui 0.5.24
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/schwad/.gem/ruby/3.2.2/gems/bloops-0.5/ext/ruby
/opt/rubies/3.2.2/bin/ruby extconf.rb
checking for -lportaudio... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/rubies/3.2.2/bin/$(RUBY_BASE_NAME)
	--with-portaudio-dir
	--without-portaudio-dir
	--with-portaudio-include
	--without-portaudio-include=${portaudio-dir}/include
	--with-portaudio-lib
	--without-portaudio-lib=${portaudio-dir}/lib
	--with-portaudiolib
	--without-portaudiolib
/opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:490:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:583:in `try_link0'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:601:in `try_link'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:819:in `try_func'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:1062:in `block in have_library'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:989:in `block in checking_for'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:354:in `block (2 levels) in postpone'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:324:in `open'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:354:in `block in postpone'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:324:in `open'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:350:in `postpone'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:988:in `checking_for'
	from /opt/rubies/3.2.2/lib/ruby/3.2.0/mkmf.rb:1057:in `have_library'
	from extconf.rb:14:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/schwad/.gem/ruby/3.2.2/extensions/arm64-darwin-22/3.2.0/bloops-0.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/schwad/.gem/ruby/3.2.2/gems/bloops-0.5 for inspection.
Results logged to /Users/schwad/.gem/ruby/3.2.2/extensions/arm64-darwin-22/3.2.0/bloops-0.5/gem_make.out

  /opt/rubies/3.2.2/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:27:in `build'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in `build_extension'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block in build_extensions'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `build_extensions'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/rubygems/installer.rb:843:in `build_extensions'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/source/rubygems.rb:200:in `install'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
  /opt/rubies/3.2.2/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing bloops (0.5), and Bundler cannot continue.

In Gemfile:
  bloops
```

logs

```
DYLD_FALLBACK_LIBRARY_PATH=.:/opt/rubies/3.2.2/lib "clang -o conftest -I/opt/rubies/3.2.2/include/ruby-3.2.0/arm64-darwin22 -I/opt/rubies/3.2.2/include/ruby-3.2.0/ruby/backward -I/opt/rubies/3.2.2/include/ruby-3.2.0 -I. -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/libyaml/include -I/opt/homebrew/opt/gdbm/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wno-error=implicit-function-declaration  -fno-common -pipe -I../../c  conftest.c  -L. -L/opt/rubies/3.2.2/lib -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/gdbm/lib -L. -fstack-protector-strong -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/gdbm/lib     -lruby.3.2  -lpthread   -lm -lportaudio "
ld: library not found for -lportaudio
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

**Comment by noahgibbs** [comment]
Ah, that looks like it's not *finding* PortAudio. Try "brew install pkg-config".

**Comment by noahgibbs** [comment]
There's also a way to fix it by overriding Homebrew paths. But it's easier to install pkg-config, if that works.

**Comment by Schwad** [comment]
Thanks Noah I'll try that on my machine shortly!

**Comment by Schwad** [comment]
ah I already had pkg-config. I'll do a bit more digging. It worked on my intel mac just wanted to ensure there wasn't an m1 problem

**Comment by Schwad** [comment]
(doing some reinstalls first out of paranoia)

**Comment by noahgibbs** [comment]
At this point, it sounds like you have this sorted out. Have you already updated the README about using Homebrew and we can close this, or should that get fixed in the docs?

**Comment by noahgibbs** [comment]
Here's what Lea did for this, for her app:

```bash
brew install portaudio && bundle config build.bloops --with-portaudio-dir=$(brew --prefix portaudio)
```

That's not a bad idea to document, even if we wind up having a "bloops optional" config that we default to.

**Comment by noahgibbs** [comment]
Okay, I think this is done. Closing. Reopen if you disagree.
