### ISSUE TITLE
bug in button_alert with events

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe#422]
Probably from me messing with how alerts work recently.

```
noah@Noahs-MBP-3 scarpe % SCARPE_HTML_RENDERER=tiranti SCARPE_BOOTSTRAP_THEME=cerulean bundle exec ./exe/scarpe examples/button_alert.rb
Error occured: /Users/noah/src/shoes/scarpe/lib/scarpe/wv/app.rb:82:in `handle_callback': undefined method `call' for nil:NilClass (NoMethodError)

      @callbacks[name].call(*args)
                      ^^^^^
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/app.rb:49:in `block in init'
	from /Users/noah/.gem/ruby/3.2.2/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:64:in `block in bind'
	from /Users/noah/.gem/ruby/3.2.2/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:45:in `webview_run'
	from /Users/noah/.gem/ruby/3.2.2/gems/webview_ruby-0.1.2/lib/webview_ruby.rb:45:in `run'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/web_wrangler.rb:389:in `run'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/app.rb:65:in `run'
	from /Users/noah/src/shoes/scarpe/lib/scarpe/wv/app.rb:35:in `block in initialize'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes/display_service.rb:71:in `block in dispatch_event'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes/display_service.rb:71:in `each'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes/display_service.rb:71:in `dispatch_event'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes/display_service.rb:176:in `send_shoes_event'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes/app.rb:147:in `run'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes.rb:84:in `app'
	from /Users/noah/src/shoes/scarpe/examples/button_alert.rb:1:in `<top (required)>'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes.rb:119:in `load'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes.rb:119:in `block in default_file_loaders'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes.rb:105:in `block in run_app'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes.rb:104:in `each'
	from /Users/noah/src/shoes/scarpe/lacci/lib/shoes.rb:104:in `run_app'
	from /Users/noah/src/shoes/scarpe/exe/scarpe:80:in `<top (required)>'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/noah/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
	from /Users/noah/.gem/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/noah/.gem/ruby/3.2.2/bin/bundle:25:in `<main>'
```

**Comment by noahgibbs** [comment]
Yup, my fault. DocumentRoot is registering the event handler for event name "OK" but it's getting rendered as "click", which is the default with no event name set. Hm
