### ISSUE TITLE
Gem build having some issues

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#563]
```
scarpe|schwimsy ⇒ gem build scarpe.gemspec
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["bin/scarpe"] are not files
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/specification_policy.rb:540:in `error'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/specification_policy.rb:316:in `validate_non_files'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/specification_policy.rb:76:in `validate_required!'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/specification_policy.rb:47:in `validate'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/specification.rb:2577:in `validate'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:297:in `build'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/package.rb:136:in `build'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/commands/build_command.rb:94:in `build_package'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/commands/build_command.rb:84:in `build_gem'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/commands/build_command.rb:75:in `execute'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:326:in `invoke_with_build_args'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:255:in `invoke_command'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:194:in `process_args'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:152:in `run'
	/opt/rubies/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:56:in `run'
	/opt/rubies/3.2.0/bin/gem:12:in `<main>'
```

I think it could have to do with this specification... `  spec.executables = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }`

**Comment by noahgibbs** [comment]
Oh, interesting. No, a different branch was working, but main branch is borked. Okay, I'll look at this.

**Comment by noahgibbs** [comment]
Ah, okay. The whimsical checkout message from a bunny commit breaks it, because you changed the exe dir from 'exe' to 'bin'. Was hard to see because of all the lines that changed quotes.

**Comment by noahgibbs** [comment]
Ah, you also got rid of the webrick dependency. That's going to break at least one example on recent versions of Ruby, which no longer package webrick.

**Comment by Schwad** [comment]
> Was hard to see because of all the lines that changed quotes.

Yeah, I mentioned in a PR I just put up that I'll be altering my editor to not format on save when working in this directory. I don't mind how our code is written and so if I'm disabling rubocop I should disable that as well!

**Comment by Schwad** [comment]
I think webrick is still there?

Alright. closing this as eagle-eyed Noah caught the newly introduced mistake that caused failures. Thank you 🦅 🙇

**Comment by noahgibbs** [comment]
Ah, Webrick moved/changed because of quoting but wasn't removed. Cool.
